### ISSUE TITLE
Remove getGameDataUsingOwnApiKey from getGameData

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#11]
In the version v1, Steam schema data was obtained by invoking a function similar to the one following:

```typescript
async getGameData(appId: string, lang: string, key?: string | undefined): Promise<IGameData> {
    if (!this.steamLanguages.includes(lang)) {
        throw 'Language selected not supported by Steam API';
    }

    let gameData: IGameData;
    const gameCachePath = SteamUtils.getGameCachePath(appId, lang);

    if (await SteamUtils.validSteamGameDataCacheExists(gameCachePath)) {
      gameData = await SteamUtils.getGameDataFromCache(gameCachePath);
    } else {
      gameData = await SteamUtils.getGameDataUsingOwnApiKey(appId, lang, key);
    } else {
      gameData = await SteamUtils.getGameDataFromServer(appId, lang, this.source);
    }
      await SteamUtils.updateGameDataCache(gameCachePath, gameData);
    }

    return gameData;
}
```

Should we delete that function and keep only the possibility of using cache / calling the `api-server`? I am not a big fan of having all the HTML parsing code stored in Celes and, as far as I know, there is no need anymore as the `api-server` can scrap data without using an Steam API Key. Is it correct @xan105?

**Comment by xan105** [comment]
I was considering removing it too (use of own web api key) because before (v1 api-server) it was easy to do a 1:1 in feature.
But v2 api tap directly in the steam network requiring steam account credentials as well as needing other 3rd party api's key (hidden description) and has its own steam web api key.

api-server does everything on its own client don't need to provide any key.
It is safe to only use cache / calling api-server (I doubt any user has use the option to use its own api  key with v1 anyway ).

**Comment by msolefonte** [comment]
Successfully removed. Closing.
