### ISSUE TITLE
Define communication between Celes and other components

### ISSUE THREAD

**Issue by msolefonte** [achievement-watcher/celes#6]
Tree approaches have been analyzed to enable communication between `celes` and other components:

1. **Creating a CLI**
  * Compile `celes` into an executable `celes.exe`.
    * The operation should be `celes.exe [command] <args>`.
    * Only progress should be shared on screen. Results, if obtained, should be obtained by reading at the database.
 * Config should be loaded from `<AW>/config/celes.json` on every execution.
2. **Using `celes` as a library**
  * Imported from every component that requires it.
  * Usage by creation of the object: `const celes = new Celes(...);`
  * Configuration passed by parameter on creation of the object.
3. **Using `celes` as a server**
  * Similar to _1._ but accepting requests from a `websocket` instead of a CLI. 
    * Hooked components should be informed of changes.
    * There has to be a program running 24/7 on background, waiting for requests.
  * Config should be loaded from `<AW>/config/celes.json` on every call.

The decided approach has been _3._

**Comment by msolefonte** [comment]
@xan105 Leaving this here to enable reference in future discussions.

I am still not comfortable with `3.` because of the program having to run 24/7 on background. There are already problems with the watchdog and I do not think users will be comfortable with another service active.

**Comment by xan105** [comment]
Yeah finally I'm not sure of celes being yet another process 🤔
(3) Even less one that would have to run continuously; There is enough _'drama'_ with watchdog doing so already.

<hr>

For (1) I do have concerns / questions :

- Compile celes into an executable celes.exe 
I'm currently using node-pkg (for watchdog) and it's a pain for the path of resources (native module, native ressources such as dll,...).
I was thinking of going back to a sandbox boxer like enigma virtual box or just don't care and ship node.exe with the js file as is (node.exe /path/to/watchdog.js)
- AW needs to be aware of the progression of the parsing and schema generation. It is a costly operation that takes a lot of time without cache on the first run. To have such a callback we 'd have to react to the output of the executable ? 
```
const child = child.spawn("celes.exe") , {stdio: ['pipe', 'pipe', 'pipe']});
let data = [];
child.stdout.on('data', (chunk) => {
    data.push(chunk);
    /*somehow show progress ?*/      
});

child.on('exit', () => {
  const output = data.join('');
/*do something with it*/
});
```
Not sure on how you were seeing the implementation but spawning celes and piping its output feels rather lackluster (in a Windows env that is).

<hr>

(2) Looking back it bugs me to have similar code for the same thing in AW and Watchdog.
And If I was to re-do it I'd probably have made a shared module for the parsing of user's achievements and schema generation.
Your thoughts on using it as a lib ?

And how gog galaxy python plugin would hook to that in this case (_since it's your end-goal I'm not forgetting about it_) ?
Before you join in. Because of the issues you had posted in AW. 
I was going to make a web api to get user's achievements (a la steam)
Add one to push achievements to the server.
AW would send merged oldest time.
Watchdog would have send on detected unlock.
Had already endpoints for fetching steam schema.
(_But all of this is only for steam, other platform regarding the schema would need to be think about due to the limitation that there is no easy public api like steam for all of them and some are just taken from local file (rpcs3, Vita3K)_)

**Comment by msolefonte** [comment]
1. About creating a CLI:

* As commented in other discussions, I never worked with Node.js turned into an executable. Like 90% of my job is related to Linux and Docker, which does not apply at all here.
* The problem with running Node.js natively is that users have to have it installed and it is another dependency, plus bugs related to different versions. I'm still going with executables because it is a problem for us but prevents problems to the users.
* I am going to ask some people I know about this, to see if someone can provide a solution.
* About progression, I already thought about that. The cli would print progression on air. Data should be read later from the local database, which should be really fast comparatively.

---

2. About the library approach:

* This approach forces `watchdog` / `showcase` / `gog-galaxy-integration` to have the library installed. In the case of the last one, this approach is harder, but data could be read directly from the database. Actually, the `watchdog` could even read only the database, being quite faster and simpler. 

---

The more I think about it, the more comfortable I am with 2.

**Comment by xan105** [comment]
>The problem with running Node.js natively is that users have to have it installed and it is another dependency, plus bugs related to different versions. I'm still going with executables because it is a problem for us but prevents problems to the **users.**

In any case we are shipping our own node.exe (wether it's boxed into a single exe or not) to avoid these concerns :)

> The more I think about it, the more comfortable I am with 2.

Actually me too 😅

>watchdog could even read only the database

Watchdog could have access to the db
This would replace %appdata%/aw/steam_cache/data 
And I could remove the option to use watchdog as another source which had user confused at what it does

**Comment by msolefonte** [comment]
Going to work with 2 by now, as we agree it is the best approach and it is easily updatable. I have also thought that I would be cool to have a optimized function to return scraped results as fast as possible, without reading / updating database. It would be interesting to have it to use it from the `watchdog`.

I am concerned about logging. If used as a library, throwing console logs may not be the best approach, and writing directly into a folder may create confuse logs due to the multiple components using the same tool. What about passing a logger on creation?

**Comment by xan105** [comment]
> What about passing a logger on creation?

It seems the easier to do

**Comment by msolefonte** [comment]
Decided to be a component. Analysis continued at #20
